---
  # Talk to all hosts just so we can learn about them...
- name: Create a EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: vmops_mmm
    instance_type: t2.large
    image: ami-da05a4a0
    region: us-east-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         #group: BotGroup
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         exact_count: 1
         monitoring: yes
         count_tag:
            Name: vm1
         instance_tags:
            Name: vm1
      register: ec2
    - name: Print all ec2 variables
      debug: var=ec2

    - add_host: 
        name: "{{ item.public_ip }}"
        groups: "vm1"
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/SEProject/vmops_mmm
      with_items: "{{ ec2.instances }}"
      
    - name: Wait for the instances to boot by checking the ssh port
      wait_for: 
        host: "{{item.public_ip}}" 
        port: 22 
        delay: 60 
        state: started
      with_items: "{{ ec2.instances }}"

- hosts: vm1
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo
  pre_tasks:
    - name: Install Python
      raw: sudo test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup:
  tasks:
    - name: install pip
      apt: pkg=python-pip state=latest
    - name: Install Boto packages
      pip: name=boto3 state=latest
    - name: Install AWS CLI
      pip: name=awscli state=latest

...